"""blog model created

Revision ID: 8b209513a985
Revises: fac81f7aa61d
Create Date: 2021-12-17 14:27:05.005720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b209513a985'
down_revision = 'fac81f7aa61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=100), nullable=True),
    sa.Column('blog_description', sa.String(length=200), nullable=True),
    sa.Column('blog_img', sa.String(length=250), nullable=True),
    sa.Column('blog_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
