"""first commit

Revision ID: fac81f7aa61d
Revises: 
Create Date: 2021-12-17 13:55:44.046515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac81f7aa61d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_title', sa.String(length=100), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_year', sa.String(length=100), nullable=True),
    sa.Column('timeline_description', sa.String(length=200), nullable=True),
    sa.Column('timeline_number', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_title', sa.String(length=100), nullable=True),
    sa.Column('work_client_name', sa.String(length=100), nullable=True),
    sa.Column('work_img', sa.String(length=250), nullable=True),
    sa.Column('work_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    op.drop_table('time_line')
    op.drop_table('service')
    # ### end Alembic commands ###
